service_name: travis-ci
language: java

cache:
  directories:
  - .autoconf
  - $HOME/.m2

sudo: required

jdk:
  - oraclejdk8

os:
  - linux

after_success:
  - ./gradlew check jacocoTestReport coveralls

after_failure:
- ./gradlew clean check --debug